'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Master_in_CS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1be12a91472231_5e329aa6b3ba1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1be12a91472231.5e329aa6b3ba1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property access() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("access", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clear_Vision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clear Vision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cpp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cpp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property css() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("css", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property html() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("html", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_of_Master_in_CS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon of Master in CS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property java() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("java", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l1_clearVision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l1_clearVision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l1_sudoku() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l1_sudoku", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l1_sudoku_ans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l1_sudoku_ans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l2_clearVision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l2_clearVision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l3_clearVision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l3_clearVision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l4_clearVision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l4_clearVision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l5_clearVision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l5_clearVision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property linux() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linux", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login_Page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login Page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manish_details() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manish details", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manish_details_i___l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manish details i & l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manish_details_i___l1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manish details i & l1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manish_other_details() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manish other details", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Master_in_CS___Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Master in CS - Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property op() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("op", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property python() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("python", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sudoku() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sudoku", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tech_Nerd___Contact_Us_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech Nerd - Contact Us.png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tech_Nerd___Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech Nerd - Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tech_Nerd___Other_networks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech Nerd - Other networks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tech_Nerd___Start_home_page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech Nerd - Start-home page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tech_Nerd_aboutUs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech Nerd aboutUs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tech_Nerd_Home_Page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech Nerd Home Page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tech_Nerd_Modes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech Nerd Modes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vbnet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vbnet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property word() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
